server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myweb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username:
    password:
  redis:
    host: localhost
    port: 6379


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.MuffinHead.model.user.pojos
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.MuffinHead.model.user.pojos

muffinhead:
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
